version: 0.7.1-{build}
configuration:
- Release
- Win7 Release
- Win8 Release
- Win8.1 Release
platform:
- Win32
- x64
os: Windows Server 2012 R2
build:
  project: dokan.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - reports@islog.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true